#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

cd frontend
node_modules/.bin/stylelint src --fix
node_modules/.bin/eslint src
cd ../backend
node_modules/.bin/eslint .
# cd frontend
# npm run test
# cd ../backend
# npm run test