#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

cd frontend
node_modules/.bin/stylelint src --fix
node_modules/.bin/eslint src
node_modules/.bin/jest
cd ../backend
node_modules/.bin/eslint .
docker exec MEVN-express npm run test
# cd frontend
# npm run test
# cd ../backend
# npm run test